@extends('layouts.app')

@section('content')

    <section id="competition-rules" style="padding-top: 140px;">
        <div class="competition-rules-inner container-space">
            <h2>Organizator</h2>
            <p>Dr. Oetker d.o.o organizuje konkurs pod nazivom &quot;Po&scaron;aljite recept (Letnje torte i kolači )&quot;. Predmet konkursa je izbor najboljih recepata za torte i kolače sa eskimko sladoledom, koji sadrže barem jedan proizvod iz C Slatka tradicija asortimana.</p>
            <h2>Opis konkursa</h2>
            <p>Konkurs traje od 01. jula do 31. jula 2024. godine.<br /><br />Konkurs se organizuje za sve posetioce sajta <a href="https://www.c-slatkatradicija.rs" style="color:#258b42;">www.c-slatkatradicija.rs</a> koji za vreme trajanja konkursa posete sajt, ispune formular za slanje recepta i prihvate prava i obaveze.<br /><br />Pri popunjavanju formulara recepta učesnici su dužni da budu prijavljeni na svoj
nalog i da unesu naziv i opis recepta, sastojke kao i korake pripreme. Uslov za učešće jeste i prihvatanje pravila konkursa, naznačenih u ovim pravilima. Slanje fotografije koja prati recepte je opciono i nije uslovno za učešće. <br>Organizator ne ograničava broj recepata koji mogu biti poslati od strane jednog učesnika.</p>
            <h2>Uslovi i ograničenja</h2>
            <p>Uslov za uče&scaron;će u konkursu jeste slanje recepata za letnje torte i kolače, koji sadrže barem jedan proizvod iz C Slatka tradicija asortimana.<br /><br />Po&scaron;iljalac recepta odgovaran je za autentičnost poslatog recepta i fotografije.<br /><br />Pravo uče&scaron;ća imaju sva lica, posetioci sajta, sa prebivaliśtem na teritoriji Republike Srbije.<br /><br />Pravo na uče&scaron;će u konkursu nemaju lica zaposlena kod organizatora, kao ni njihove porodice, niti lica koja su na bilo koji način uključena u priređivanje konkursa.<br /><br />Organizator zadržava pravo da ne objavi svaki recept koji ne zadovoljava uslove konkursa navedene u ovim pravilima, kao ni recepte koji sadrže neprimerene tekstove i neprikladne fotografije.<br /><br />Organizator ne snosi odgovornost ukoliko dođe do prekida konkursa usled uticaja vi&scaron;e sile koju nije mogao sprečiti.<br /><br />Organizator ne preuzima odgovornost za bilo kakvu &scaron;tetu koja nastane zloupotrebom ovog konkursa, a koja se na taj način od strane učesnika ili trećih lica nanese bilo drugim učesnicima konkursa, bilo trećim licima.<br /><br />Organizator zadržava pravo javnog objavljivanja tekstova i fotografija recepata pristiglih od strane učesnika konkursa na dru&scaron;tvenim mrežama Organizatora.<br /><br />Učesnici su upoznati sa tim i samim tim &scaron;to učestvuju u nagradnom konkursu, saglasni su da njihovi recepti i fotografije recepata budu objavljeni na dru&scaron;tvenim mrežama Organizatora.</p>
            <h2>Pobednički recepti i nagrade</h2>
            <img src="{{ asset('images/Uslovi-i-pravila-konkursa-poklon-paket.jpeg') }}" alt="Poklon paket - C Slatka tradicija, Poklon paket - C Slatka tradicija" style="width: 100%; margin-bottom: 20px;">
            <p>Na kraju konkursa žiri u sastavu Miloš Savić, Jana Babović i Nikola Špička će od svih pristiglih recepata tokom konkursa izabrati 4 pobednička recepta, na osnovu kvaliteta, originalnosti i kreativnosti. Recepti odabrani kao pobednički osvajaju po 1 poklon paket. Svaki poklon paket čini: promotivno pakovanje (sadrži: 1 brendiranu desertnu činiju, 2 C Pudinga sa ukusom jagode, 2 C Pudinga sa ukusom vanile, 2 C Pudinga sa ukusom čokolade), C Kakao prah, C Kokos, C Šlag krem sa ukusom vanile 180 g i C Šlag krem sa ukusom čokolade 180 g.<br /><br />Pobednički recepti će po zavr&scaron;etku konkursa biti objavljeni na sajtu <a href="https://www.c-slatkatradicija.rs" style="color:#258b42;">www.c-slatkatradicija.rs</a> na stranici <a href="https://www.c-slatkatradicija.rs/nagradni-konkursi/" style="color:#258b42;">Nagradni konkursi</a>, a najkasnije 7 dana po zavr&scaron;etku konkursa. Po odabiru pobedničkih recepata, organizator će kontaktirati dobitnike putem emaila, kako bi se dogovorili oko slanja nagrade.</p>
            <h2>Isporuka poklon paketa</h2>
            <p>Organizator će pobednicima dostaviti poklon pakete, najkasnije u toku 15 radnih dana nakon &scaron;to je stupio u kontakt sa pobednicima.<br /><br />Organizator ne snosi odgovornost ukoliko ne može da stupi u kontakt sa učesnicima čiji su recepti odabrani kao pobednićki u roku određenom u ovim pravilima.</p>
        </div>
    </section>

@endsection
