@extends('layouts.app')

@section('content')
    <section id="privacy-note-hero"></section>

    <section id="privacy-note-content">
        <div class="privacy-note-content-inner container-space">
            <h1>Pravna napomena</h1>
            <p>Dr. Oetker (u daljem tekstu „Dr. Oetker“) vodi ovu internet stranicu. Na ovoj internet stranici želimo da Vas informišemo o Dr. Oetker-u, kao i o našim proizvodima i aktivnostima.Pravna napomena reguliše uslove korišćenja ove internet stranice. U pojedinačnim slučajevima, pored poštovanja pravnih pravila sadržanih u ovoj pravnoj napomeni, obavezno je poštovanje i dodatnih pravila. Primera radi, prilikom otvaranja internet stranica koje su dostupne samo registrovanim korisnicima, moraju se poštovati dodatna pravila, o kojima na odgovarajućim mestima postoje dodatne napomene.</p>
            <p class="pp-dot">.</p>
            <h2>1. Korišćenje internet stranice</h2>
            <p>Ovlašćeni ste, da sadržaje sa internet stranice Dr. Oetker-a pregledate, snimate i preuzimate u privatne ili novinarske svrhe. Za umnožavanje, širenje i/ili objavljivanje sadržaja sa ove stranice na bilo koji drugi način, i u ostale svrhe, potrebna je prethodna pismena saglasnost Dr. Oetker-a. U slučaju davanja saglasnosti od strane Dr. Oetker-a, korišćenje sledi bez honorara, pri čemu se mora jasno i u čitkom obliku navesti napomena o autorskim pravima:</p>
            <h4>© Dr. Oetker d.o.o.</h4>
            <p>Sve ostale radnje korišćenja su izričito zabranjene. Zabrana naročito važi za izmenu i obradu sadržaja ili delova sadržaja koji su objavljeni na internet stranici Dr. Oetker-a.Pravna napomena je podložna izmenama. Stoga, ukoliko je to potrebno, ista se može prilagoditi izmenjenim okolnostima i važećoj zakonskoj regulativi. Korišćenjem ove internet stranice prihvatate da se pridržavate uslova propisanih pravnom napomenom koja važi u trenutku korišćenja internet stranice.Kršenje pravila sadržanih u ovoj pravnoj napomeni obavezuje na momentalni prestanak korišćenja naše internet stranice, kao i otklanjanje posledica koje na taj način prouzrokujete, tj. potrebno je prestati sa radnjama korišćenja i uništiti eventualno sačinjene kopije. U tom slučaju Dr. Oetker zadržava pravo na naknadu eventualne štete.</p>
            <h2>2. Pravo intelektualne svojine</h2>
            <p> Sadržaji koje možete skinuti sa internet stranice zaštićeni su autorskim pravom. Zaštiti naročito podležu sadržajna struktura internet stranice, kao i tekstovi, fotografije, audio i video fajlovi i baze podataka.Nazivi proizvoda i njihov izgled koji su objavljeni na internet stranici, između ostalog,  zaštićeni su pravima koja se odnose na žigove i/ili pravo konkurencije. Zaštita se naročito odnosi na oznake firmi i žigova, kao i opremu pakovanja (Layout). Takođe, naši proizvodi su zaštićeni i na drugi način, kao na primer: pravima kojima se štite uzorci ukusa, upotrebe ili patenta.Svako neovlašćeno korišćenje internet stranice Dr. Oetker-a, naziva proizvoda, izgleda proizvoda ili samog proizvoda, predstavlja povredu autorskih prava, prava žigova, konkurencije ili drugih prava industrijske svojine.</p>
            <h2>3. Odgovornost za sopstvene sadržaje</h2>
            <p> Odgovornost Dr. Oetker-a za štetu prouzrokovanu korišćenjem ove internet stranice ograničena je na naknadu štete prouzrokovane krajnjom nepažnjom sa naše strane dok u slučaju povrede života, tela ili zdravlja ljudi, postoji odgovornost Dr. Oetker-a ukoliko je šteta prouzrokovana i običnom nepažnjom. Kod povrede bitnih obaveza iz ugovora, nastalih običnom nepažnjom, Dr. Oetker odgovara do visine uobičajene i predvidive štete. Odgovornost za proizvode ostaje u skladu sa važećim zakonom. Navedeno ograničenje odgovornosti se primenjuje i na rad sa ostalim internet stranicama i preuzimanje sadržaja sa istih. Molimo da se pre preuzimanja fajlova i informacija sa naše internet stranice sami pobrinete za zaštitu od virusa jer Dr. Oetker ne odgovara za eventualnu štetu koju možete pretrpeti po tom osnovu.</p>
            <h2>4. Odgovornost za strane sadržaje</h2>
            <p>Internet stranica Dr. Oetker-a može da sadrži veze (takozvane linkove) prema drugim internet stranicama, koje vode treća lica („tuđe internet stranice“). Osim toga, na našim internet stranicama mogu se naći forumi sa diskusijama (takozvani četovi „“chats“), na kojima treća lica daju svoja mišljenja o raznim temama („tuđi prilozi“).Dr. Oetker ne prisvaja sadržaje tuđih internet stranica kao ni tuđih priloga i komentara, štaviše, Dr. Oetker se ovim putem izričito ograđuje od takvih sadržaja.Ukoliko se utvrdi, da tuđe internet stranice ili tuđi prilozi objavljeni na ovoj internet stranici krše zakonske odredbe ili prava trećih lica, takvi linkovi ili prilozi će biti obrisani, ukoliko je to pravno i tehnički moguće.Molimo da ukoliko uočite ovakve sadržaje da nam dostavite odgovarajuće napomene u tom smislu, kako bismo preduzeli odgovarajuće radnje za njihovo uklanjanje sa internet stranice.Zabranjeno je na forumima naše internet stranice postavljati materijal koji nije u skladu sa zakonom, kao i materijal koji krši prava trećih lica. Zabrana naročito važi za materijal kojim se kleveta, potcenjuju prava trećih lica, kao i pornografski materijal.</p>
        </div>
    </section>
@endsection
