@extends('layouts.app')

@section('content')
    <section id="privacy-policy-hero"></section>

    <section id="privacy-note-content">
        <div class="privacy-note-content-inner container-space privacy-policy-inner">
            <h1>Politika zaštite podataka</h1>
            <h3>Napomena o zaštiti podataka</h3>
            <p>Dr. Oetker d.o.o. (u daljem tekstu „Dr. Oetker“) poštuje sferu privatnosti i zaštite podataka svih lica. Imajući to u vidu, Dr. Oetker veoma ozbiljno shvata zaštitu ličnih podataka. U skladu sa odredbama člana 23. Zakona o zaštiti podataka o ličnosti ["Sl. glasnik RS", br. 87/2018 – u daljem tekstu: Zakon] Dr. Oetker d.o.o Šimanovci, ulica Vuka Karadžića br. 13, MB: 17328573, PIB: 100137621, kao Rukovalac podacima, pre otpočinjanja sa prikupljanjem i daljom obradom podataka o ličnosti vezano za učešće u nagradnom konkursu „Pošaljite recept“ obaveštava lica čije će lične podatke obrađivati o svim okolnostima bitnim za obradu podataka.</p>
            <h6>1. Izbegavanje upotrebe podataka i štedljivost podataka</h6>
            <p>Dr. Oetker se pridržava principa izbegavanja upotrebe podataka o ličnosti kao i štedljivosti tih podataka. To znači da će se prikupljanje, obrada i korišćenje ličnih podataka vršiti u najmanjoj mogućoj meri.</p>
            <h6>2. Lični podaci, saglasnost i svrha</h6>
            <p>Podaci o ličnosti će biti prikupljani, obrađivani, korišćeni i objavljivanji samo nakon davanja prethodne saglasnosti lica o čijim se ličnim podacima u konkretnom slučaju radi.Svrha prikupljanja i obrade podataka jeste učestvovanje u nagradnom konkursu radi  dodele nagrada učesnicima konkursa, a pravni osnov za obradu sadržan je u članu 12. stav 1. tačka 1. Zakona o zaštiti podataka o ličnosti, kao i u skladu sa članom 232. Zakona o obligacionim odnosima. Lični podaci će biti upotrebljeni samo u svrhu i u onom obimu, za koje je saglasnost data. S tim u vezi, korisnici će biti informisani o Dr. Oetker proizvodima i uslugama nakon davanja odgovarajuće saglasnosti.Dr. Oetker će obrađivati sledeće lične podatke učesnika u nagradnom konkursu: [1] ime i prezime, [2] adresu prebivališta, [3] email adresu, [4] broj telefona. Lični podaci dobitnika će biti upotrebljeni isključivo u svrhu slanja nagrada.O eventualnoj nameri da Dr. Oetker obrađuje podatke u svrhu koja je različita od svrhe za koju su podaci prikupljeni, Dr. Oetker će korisniku, odnosno licu na koje se podaci odnose pre započinjanja dalje obrade pružiti informacije o toj drugoj svrsi, kao i sve ostale bitne informacije koje su navedene.</p>
            <h6>3. Automatski generisani podaci</h6>
            <p>U okviru korišćenja internet stranice Dr. Oetker-a može doći do automatske obrade ličnih podataka. Pod ličnim podacima se posebno ubrajaju ime provajdera, IP-adresa, tip pretraživača i operativnog sistema, kao i posećene internet stranice uključujući eventualne ključne reči i internet stranice sa kojih je izvršena poseta ove internet stranice. Obrada usleđuje u svim napred navedenim slučajevima i ista je anonimna, tj. identifikacija ličnih podataka (=identifikacija) je isključena.</p>
            <h6>4. Cookies – Kolačići</h6>
            <p>Pri korišćenju internet stranice Dr. Oetker-a mogu nastati manji tekstualni fajlovi koji se memorišu u kompjuteru lica koje stranici pristupa (tzv. „Cookies“). Dr. Oetker koristi Cookies kako bi olakšao odnosno poboljšao korišćenje svoje internet stranice.Cookies, koji nastaju prilikom pristupanja ovoj internet stranici dozvoljavaju identifikaciju korisnika i oni se ponovo aktiviraju za vreme posete našoj internet stranici, s tim što se pri tom ne memorišu lični podaci korisnika. U cilju pružanja što bolje usluge, na internet stranici Dr. Oetker upotrebljavaju se "Permanent-Cookies" i "Session-Cookies".U Permanent-Cookies se memorišu podaci (trajanje memorisanja je 2 godine) kako bi se korisnicima omogućilo što komfornije korišćenje internet stranice, nevezano za trenutnu posetu. Memorisani podaci se koriste samo u navedenu svrhu.Deaktiviranje navedenih Cookies nema uticaja na korišćenje ove internet stranice.Podaci koji su sačuvani u Session-Cookies važe samo za trenutnu posetu našoj internet stranici i služe da omoguće neograničeno korišćenje usluga Dr. Oetker-a, kao i što komfornije korišćenje naše internet stranice prilikom trenutne posete istoj.Pri deaktiviranju Session-Cookies, Dr. Oetker ne garantuje da će korisnicima biti na raspolaganju sve usluge njegove internet stranice bez ograničenja.Ukoliko korisnici ne žele da upotrebljavaju Cookies, mogu izmeniti podešavanja pretraživača (informacije vezane za to mogu se naći u funkcijama za pomoć i meni listi internet pretraživača). Cookies koji su već memorisani na kompjuteru korisnika, mogu se ukloniti brisanjem privremenih internet stranica.</p>
            <h6>5. Društvene mreže</h6>
            <p>Na internet stranici Dr. Oetker-a nalaze se upućivanja (linkovi) na eksterne socijalne mreže kao na primer Facebook („Social Plugins“). Linkovi sadrže upućene funkcije, posebno posredovanje informacija i podataka korisnika. Napominjemo, da se ove funkcije ne aktiviraju samom posetom naše internet stranice, već klikom na određeni link. Nakon klika na određeni link aktiviraju se Plugins odgovarajućih mreža i pretraživač korisnika uspostavlja direktno povezivanje sa njihovim serverima.Ukoliko za vreme posete internet stranice Dr. Oetker-a dođe do aktiviranja određenih linkova, može doći do posredovanja korisničkih podataka odgovarajućoj mreži, kao i njihove obrade od strane te mreže. Ako za vreme posete naše internet stranice korisnik klikne na određeni link i ukoliko je korisnik istovremeno ulogovan preko svog korisničkog naloga na određenu mrežu, informacija da je korisnik posetio našu internet stranicu može biti prosleđena toj mreži i tamo memorisana. Kako bi korisnici sprečili dodeljivanje podataka sa svog naloga odgovarajućoj mreži, korisnik se mora pre klika i aktivacije određenog linka izlogovati sa svog naloga.Svrha i obim prikupljanja podataka od strane socijalnih mreža kao i tamošnja dalja obrada i dalje korišćenje podataka, kao i prava vezana za to i mogućnosti zaštite sfere privatnosti korisnik može pročitati u Napomenama o zaštiti podataka odgovarajuće mreže. Za obradu podataka do koje može doći klikom na link, odgovornost ne snosi Dr. Oetker već samo odgovarajuća društvena mreža.</p>
            <h6>6. Pristup trećih lica ličnim podacima</h6>
            <p>Treća lica nemaju pristup ličnim podacima korisnika, sem ukoliko je to neophodno radi ostvarivanja svrhe prikupljanja podataka, odnosno radi obaveštavanja korisnika o osvojenim nagradama i samog slanja nagrada na adrese korisnika. Ukoliko to bude slučaj Dr. Oetker će se pobrinuti da se treća lica pridržavaju relevantnih zakonskih propisa o zaštiti podataka, kao i obaveza koje proizilaze iz ove napomene o pravilima o zaštiti podataka.Dr. Oetker lične podatke neće prodavati ili upotrebiti na drugi način. U slučajevima propisanim zakonom, i na zahteve ovlašćenih službenih lica i državnih organa, Dr. Oetker će istima saopštavati podatke korisnika.</p>
            <h6>7. Sigurnost</h6>
            <p>Dr. Oetker je preduzeo tehničke, kadrovske i organizacione mere kako bi zaštitio lične podatke korisnika od zloupotreba, gubitka, uništenja, izmene, neovlašćenog otkrivanja ili pristupa podacima o ličnostima.</p>
            <h6>8. Deca</h6>
            <p>Dr. Oetker se ne bavi prikupljanjem ličnih podataka koji se odnose na lica mlađa od 15 godina. Ukoliko su na internet stranici posredovani takvi podaci bez saglasnosti roditelja ili njihovih staratelja, ti podaci će odmah biti izbrisani. S tim u vezi, uklanjanje takvih podataka od strane Dr. Oetker-a zavisi od odgovarajućih obaveštenja i upućivanja datih od strane roditelja ili staratelja.</p>
            <h6>9. Brisanje, rok i opoziv</h6>
            <p>Dr. Oetker će izvršiti brisanje ličnih podataka ukoliko svrha poslovanja koja je vezana za te podatke prestane ili relevantni zakonski propisi o zaštiti podataka to zahtevaju. Dr. Oetker će podatke koji su prikupljeni u svrhu nagradne igre izbrisati nakon završetka iste ukoliko korisnik nije dao saglasnost za dalje prikupljanje, obradu i korišćenje ličnih podataka. U slučaju date saglasnosti lični podaci će biti izbrisani nakon opoziva saglasnosti ili prestanka svrhe radi koje je saglasnost data.Korisnik ima pravo na opoziv pristanka u bilo koje vreme, s tim što opoziv pristanka ne utiče na dopuštenost obrade na osnovu pristanka pre opoziva. Opoziv pristanka korisnik može da podnese putem emaila info@c-slatkatradicija.rs</p>
            <h6>10. Pristup, ispravka i brisanje</h6>
            <p>Korisnik čije podatke Dr. Oetker obrađuje ima pravo da u skladu sa članom 26 Zakona o zaštiti podataka o ličnosti zahteva pristup podacima, pravo na ispravku ili brisanje podataka o ličnosti u skladu sa čl. 29. i 30. Zakona, pravo na ograničenje obrade u skladu sa članom 31. Zakona, prava na prenosivost podataka u skladu sa članom 36. Zakona, kao i pravo na prigovor u skladu sa članom 37. Zakona.</p>
            <h6>11. Pritužba povereniku</h6>
            <p>Korisnik čije podatke Dr. Oetker obrađuje ima pravo da u skladu sa članom 82. Zakona podnese pritužbu Povereniku za informacije od javnog značaja i zaštitu podataka o ličnosti, ako smatra da je obrada podataka o ličnosti izvršena suprotno odredbama Zakona.</p>
            <h6>12. Automatizovano donošenje pojedinačnih odluka i profilisanje</h6>
            <p>Automatizovano donošenje odluke, uključujući profilisanje, kao bilo koji oblik automatizovane obrade koji se koristi da bi se ocenilo određeno svojstvo ličnosti, može se primeniti prema licu čije podatke Rukovalav podataka obrađaje samo u izuzetnim slučajevima i pod uslovima i na način iz člana 38. Zakona, kao i u skladu sa svrhom Zakona i njegovim zaštitnim odredbama koje se odnose na ličnosti čiji se podaci štite.</p>
            <h6>13. Hiperlinkovi</h6>
            <p>Internet stranica Dr. Oetker-a može sadržati hiperlinkove, tj. elektronska poprečna upućivanja preko kojih se mogu pretraživati internet stranice drugih preduzeća. Prilikom posete linkovane internet stranice, ne primenjuje se ova napomena o zaštiti podataka, već odredbe o zaštiti podataka koje sadrži posećena linkovana stranica.</p>
            <h6>14. Izmene napomene o zaštiti podataka</h6>
            <p>Ažuriranje napomene o zaštiti podataka se vrši ukoliko je to potrebno radi prilagođavanja izmenjenim okolnostima ili usled promene propisa. Korisnik koji poseti našu internet stranicu je saglasan sa navedenim prilagođavanjem i verzijom napomene koja važi u trenutku posećivanja.</p>
            <h6>15. Ovlašćeni za zaštitu podataka</h6>
            <p>Za pitanja vezana za prikupljanje, obradu ili korišćenje ličnih podataka, za informacije, ispravke, blokiranje ili brisanje podataka korisnici se mogu obratiti licu određenom za zaštitu podataka o ličnosti Milošu Saviću na sledeću adresu:</p>
        </div>
    </section>
@endsection
